name: disaster_admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-114.0.dev <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.0
  location: ^6.0.1
  flutter_svg: ^2.0.10+1
  flutter_compass: ^0.8.0
  flutter_polyline_points: ^2.0.0
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  zego_uikit_prebuilt_video_conference: ^2.7.4
  url_launcher: ^6.2.6
  weather: ^3.1.1
  bloc: ^8.1.4
  geolocator: ^11.0.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  firebase_storage: ^11.7.3
  firebase_messaging: ^14.9.1
  shared_preferences: ^2.2.3
  # Utility Packages
  http: ^1.1.0
  logger: ^2.0.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  connectivity_plus: ^5.0.1
  change_app_package_name: ^1.1.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1
  image_picker_ios: ^0.8.10+1

  google_fonts: ^6.2.1
  share_plus: ^9.0.0
  flutter_sliding_up_panel: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  firebase_database: ^10.5.4
  shake_event: ^0.0.9
  sensors_plus: ^5.0.1
  shake: ^1.0.1
  vibration: ^1.8.4

  # Update Google Play services libraries



  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets2/images/appicon.png"

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - Assets2/Images/
    - Assets2/Images/mintemp.png
    - Assets2/Images/maxtemp.png
    - Assets2/Images/thunderstorm.png
    - Assets2/Images/
    - Assets2/logos/
    - Assets2/icons/brands/
    - Assets2/Images/content/
    - Assets2/Images/banners/
    - Assets2/Images/reviews/
    - Assets2/Images/products/
    - Assets2/icons/categories/
    - Assets2/Images/animations/
    - Assets2/icons/payment_methods/
    - Assets2/Images/on_boarding_images/
     

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: Assets2/fonts/Poppins-Light.ttf
          weight: 300
        - asset: Assets2/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: Assets2/fonts/Poppins-Italic.ttf
          style: italic
        - asset: Assets2/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: Assets2/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: Assets2/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: Assets2/fonts/Poppins-Bold.ttf
          weight: 800
flutter_native_splash:
  color : "#FFFFFF"
  color_dark: "#272727"
  image: "Assets2/logos/t-store-splash-logo-black.png"
  image_dark: "Assets2/logos/t-store-splash-logo-white.png"

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: "Assets2/logos/t-store-splash-logo-black.png"
    image_dark: "Assets2/logos/t-store-splash-logo-white.png"
  web: false